spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

# 공통 설정
logging:
  level:
    org.springframework.web: INFO
    sun.rmi: INFO

# Swagger 공통 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# CORS 공통 설정
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173}
